# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulate',
            old_name='catagory',
            new_name='category',
        ),
    ]
