# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formulate', '0002_auto_20170417_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=50)),
                ('EName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormulateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.CharField(max_length=200)),
                ('formulate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulate.Formulate')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=50)),
                ('EName', models.CharField(max_length=50)),
            ],
        ),
    ]
