# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulate', '0005_auto_20170417_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='EName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='EName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
