# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulate', '0006_auto_20170417_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulatedetails',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formulate.Materials'),
        ),
        migrations.AlterField(
            model_name='formulate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulate.Category'),
        ),
    ]
