# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulate', '0008_formulatedetails_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulatedetails',
            name='unit',
            field=models.CharField(default='公克', max_length=10),
        ),
    ]
