# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulate', '0009_auto_20170417_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulate',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formulatedetails',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
