# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulate', '0012_auto_20170417_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulate',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Python36_WS\\tCooking\\upload'),
        ),
    ]
